version: "3.8"

networks:
  corp:
    driver: bridge

services:
  graphql:
    container_name: graphql
    build:
      context: ./
      dockerfile: ./graphql/Dockerfile
      args:
        NODE_ENV: "development"
        PORT: 3000
        BUILD_FLAG: ""
    image: gql-server:nx-dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: "development"
      PORT: 3000
    networks:
      - corp
    restart: on-failure
